configName: wfi32_curiosity
folderName: AzureDemo_WFI32-Curiosity
format_version: v1.0
frameworkPath: ../../../../Harmony3
processor: PIC32MZ1025W104132
projectName: AzureDemo_WFI32-Curiosity
settings:
  PackageFilter: crypto;dev_packs;net;core;bsp;quick_docs;usb;cryptoauthlib;wireless_wifi;csp;harmony-services;wireless_system_pic32mzw1_wfi32e01;wireless_apps_winc3400;wireless_apps_winc1500;wireless_apps_pic32mzw1_wfi32e01;azure_rtos
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: ./dev_packs/arm/CMSIS/5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: ./dev_packs/Microchip/PIC32MZ-W_DFP/1.6.217/atdf/PIC32MZ1025W104132.atdf
